-- CreateEnum
CREATE TYPE "APPOINTMENTSTATUS" AS ENUM ('COMPLETED', 'PENDING', 'CANCELLED');

-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "status" "APPOINTMENTSTATUS" NOT NULL DEFAULT 'PENDING';
